version: '3.3'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: soar
      MONGO_INITDB_ROOT_PASSWORD: soar-password
  redis_service:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data
  fronend:
    build: ./soar-frontend
    volumes:
      - ./soar-frontend:/src
      - /src/node_modules
    ports:
      - '8001:8001'
    command: npm run dev
    environment:
      NODE_ENV: production
      APP_PORT: 8001
  backend:
    build: ./soar-backend
    volumes:
      - ./soar-backend:/src
      - /src/node_modules
    ports:
      - '8002:8002'
    command: flask run --host=0.0.0.0 --port=8002
    environment:
      NODE_ENV: production
    depends_on:
      - redis_service
      - mongo
volumes:
  cache:
    driver: local
